from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from miner.agent_v1.artifact_models import Artifact, SourceRef

from .models import AgentV1ValidationFinding


VALID_ROLES = {"input", "result", "method", "interpretation", "metadata"}


def run_grounding_checks(artifact: Artifact | None, source_payload: dict[str, Any] | None) -> list[AgentV1ValidationFinding]:
    if artifact is None:
        return []
    if not source_payload:
        return _assign_finding_ids(
            [
                AgentV1ValidationFinding(
                    pass_name="grounding",
                    dimension="source_payload",
                    severity="critical",
                    target_type="source_payload",
                    message="No source_payload.json was provided; source refs cannot be validated.",
                    suggestion="Provide the source_payload.json generated by miner.agent_v1.",
                    metadata={"code": "missing_source_payload"},
                )
            ]
        )
    span_ids = {
        str(span.get("span_id"))
        for span in source_payload.get("spans", []) or []
        if span.get("span_id")
    }
    findings: list[AgentV1ValidationFinding] = []

    for claim in artifact.logic.claims:
        source_refs = list(claim.sources)
        if not source_refs and not claim.evidence_ids:
            findings.append(
                _finding(
                    "critical",
                    "claim_grounding",
                    "Claim has no sources or evidence IDs.",
                    "claim",
                    claim.claim_id,
                    code="no_source_refs",
                )
            )
        findings.extend(_check_refs(source_refs, span_ids, "claim", claim.claim_id))

    for evidence in artifact.evidence.records:
        if not evidence.source_refs:
            findings.append(
                _finding(
                    "critical",
                    "evidence_grounding",
                    "Evidence record has no source refs.",
                    "evidence",
                    evidence.evidence_id,
                    code="no_source_refs",
                )
            )
        findings.extend(_check_refs(evidence.source_refs, span_ids, "evidence", evidence.evidence_id))

    for experiment in artifact.logic.experiments:
        findings.extend(_check_refs(experiment.source_refs, span_ids, "experiment", experiment.experiment_id))

    return _assign_finding_ids(findings)


def _check_refs(
    source_refs: Iterable[SourceRef],
    known_span_ids: set[str],
    target_type: str,
    target_id: str,
) -> list[AgentV1ValidationFinding]:
    findings: list[AgentV1ValidationFinding] = []
    for ref in source_refs:
        if ref.role not in VALID_ROLES:
            findings.append(
                _finding(
                    "major",
                    "source_ref_role",
                    f"Invalid source ref role: {ref.role}.",
                    target_type,
                    target_id,
                    code="invalid_source_role",
                )
            )
        if not ref.span_ids and ref.source_type == "span":
            findings.append(
                _finding(
                    "major",
                    "source_ref_span",
                    "Span source ref has no span IDs.",
                    target_type,
                    target_id,
                    code="missing_source_span",
                )
            )
        for span_id in ref.span_ids:
            if span_id not in known_span_ids:
                findings.append(
                    _finding(
                        "critical",
                        "source_ref_span",
                        f"Source ref points to missing span ID: {span_id}.",
                        target_type,
                        target_id,
                        code="missing_source_span",
                        ref_id=ref.source_id,
                        span_id=span_id,
                    )
                )
    return findings


def _finding(
    severity: str,
    dimension: str,
    message: str,
    target_type: str,
    target_id: str,
    *,
    evidence_span: str | None = None,
    code: str,
    **metadata,
) -> AgentV1ValidationFinding:
    return AgentV1ValidationFinding(
        pass_name="grounding",
        dimension=dimension,
        severity=severity,  # type: ignore[arg-type]
        target_type=target_type,
        target_id=target_id,
        message=message,
        evidence_span=evidence_span,
        suggestion=_suggestion_for_code(code),
        metadata={"code": code, **metadata},
    )


def _suggestion_for_code(code: str) -> str:
    return {
        "missing_source_payload": "Pass the miner run source_payload.json into validator.agent_v1.",
        "invalid_source_role": "Use one of the allowed source roles.",
        "missing_source_span": "Point the source ref to a span ID present in source_payload.json.",
        "no_source_refs": "Add source refs grounded in the provided source payload.",
    }.get(code, "Repair the source-ref contract.")


def _assign_finding_ids(findings: list[AgentV1ValidationFinding]) -> list[AgentV1ValidationFinding]:
    for index, finding in enumerate(findings, start=1):
        finding.finding_id = f"G{index:03d}"
    return findings
